version: '3'
services:
  database:
    build:
      context: .
      dockerfile: Dockerfile.postgresql
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '12345678'
      POSTGRES_DB: 'postgres'
    volumes:
      - database-data:/var/lib/postgresql/data
    networks:
      - nestpost

  nestjs:
    build:
      context: .
      dockerfile: Dockerfile.nestjs
    ports:
      - '3000:3000'
    depends_on:
      - database
    environment:
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_USERNAME: 'postgres'
      DB_PASSWORD: '12345678'
      DB_DATABASE: 'postgres'

    networks:
      - nestpost

volumes:
  database-data:

networks:
  nestpost:
